### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by wladich** [rnbdev/FishPyPano#4]
On version from master I get following output:
```
$ python stitch.py -i IMG_20170901_173311.JPG -c calib_data.json
Loaded calibration data..
Projecting fisheye images to equirectangular projection..
Projecting left fisheye image..
Projecting right fisheye image..
Done projecting, starting stitching..
Traceback (most recent call last):
  File "stitch.py", line 108, in <module>
    overlap_y_min = np.where(zero_channel == 0)[0].min()
  File "/home/w/tmp/FishPyPano/lib/python3.6/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```
Attached is archive with calibration points and calib_data

I created points with other tool, not html you provide, but result seems to be sane to me
[data.zip](https://github.com/rnbdev/FishPyPano/files/1923123/data.zip)

**Comment by smichaud** [comment]
Any update on this issue? I got the exact same problem. I suspect it could be cause by library versions... @rnbguy could you share the version you use (Python, OpenCV, tqdm...). 

You could also provide a calibration file and an image that work, so we can validate that the code works on our machine.

Thank you
